/*
 * Copyright (C) 202    @Override
    public int getWidth(ImageObserver observer) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public int getHeight(ImageObserver observer) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public ImageProducer getSource() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public Graphics getGraphics() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public Object getProperty(String name, ImageObserver observer) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
4 henrr
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.HenrrySS.benchmarkmaven.Views;

import com.HenrrySS.benchmarkmaven.controllers.CribaEratostenes;
import com.HenrrySS.benchmarkmaven.controllers.Permutacion;
import com.HenrrySS.benchmarkmaven.controllers.ProductoMatrices;
import com.HenrrySS.benchmarkmaven.controllers.QuickSort;
import com.HenrrySS.benchmarkmaven.controllers.Reporte;
import javax.swing.ImageIcon;

/**
 *
 * @author henrr
 */
public class FRMBenchmark extends javax.swing.JFrame {

    /**
     * Creates new form Benchmark
     */
    public FRMBenchmark() {
        initComponents();
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/HenrrySS/benchmarkmaven/resources/benchmarking.png"));
        this.setIconImage(icon.getImage());
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button1 = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnQuickSort = new javax.swing.JButton();
        btnMultiplicacion = new javax.swing.JButton();
        btnPermutaciones = new javax.swing.JButton();
        btnCriba = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();
        lblCheckQuickSort = new javax.swing.JLabel();
        lblCheckMultiplicacion = new javax.swing.JLabel();
        lblCheckCriba = new javax.swing.JLabel();
        lblCheckPermutaciones = new javax.swing.JLabel();

        button1.setLabel("button1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Prueba de Rendimiento");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Benchmark");

        btnQuickSort.setText("QuickSort");
        btnQuickSort.setPreferredSize(new java.awt.Dimension(149, 48));
        btnQuickSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuickSortActionPerformed(evt);
            }
        });

        btnMultiplicacion.setText("Multiplicación");
        btnMultiplicacion.setPreferredSize(new java.awt.Dimension(149, 48));
        btnMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicacionActionPerformed(evt);
            }
        });

        btnPermutaciones.setText("Permutaciones");
        btnPermutaciones.setPreferredSize(new java.awt.Dimension(149, 48));
        btnPermutaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPermutacionesActionPerformed(evt);
            }
        });

        btnCriba.setText("Criba de Eratostenes");
        btnCriba.setMaximumSize(new java.awt.Dimension(149, 48));
        btnCriba.setMinimumSize(new java.awt.Dimension(149, 48));
        btnCriba.setPreferredSize(new java.awt.Dimension(149, 48));
        btnCriba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCribaActionPerformed(evt);
            }
        });

        btnReporte.setText("Reporte");
        btnReporte.setEnabled(false);
        btnReporte.setPreferredSize(new java.awt.Dimension(149, 48));
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });

        lblCheckQuickSort.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/HenrrySS/benchmarkmaven/resources/check.png"))); // NOI18N
        lblCheckQuickSort.setLabelFor(btnQuickSort);
        lblCheckQuickSort.setEnabled(false);
        lblCheckQuickSort.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblChangeProperty(evt);
            }
        });

        lblCheckMultiplicacion.setIcon(new javax.swing.ImageIcon("F:\\HenrrySS\\Descargas\\check.png")); // NOI18N
        lblCheckMultiplicacion.setLabelFor(btnMultiplicacion);
        lblCheckMultiplicacion.setEnabled(false);
        lblCheckMultiplicacion.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblChangeProperty(evt);
            }
        });

        lblCheckCriba.setIcon(new javax.swing.ImageIcon("F:\\HenrrySS\\Descargas\\check.png")); // NOI18N
        lblCheckCriba.setLabelFor(btnCriba);
        lblCheckCriba.setEnabled(false);
        lblCheckCriba.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblChangeProperty(evt);
            }
        });

        lblCheckPermutaciones.setIcon(new javax.swing.ImageIcon("F:\\HenrrySS\\Descargas\\check.png")); // NOI18N
        lblCheckPermutaciones.setLabelFor(btnPermutaciones);
        lblCheckPermutaciones.setEnabled(false);
        lblCheckPermutaciones.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblChangeProperty(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnQuickSort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(39, 39, 39)
                        .addComponent(lblCheckQuickSort))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnMultiplicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(39, 39, 39)
                        .addComponent(lblCheckMultiplicacion))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnPermutaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(39, 39, 39)
                        .addComponent(lblCheckPermutaciones))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCriba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(39, 39, 39)
                        .addComponent(lblCheckCriba)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btnReporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(47, 47, 47))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQuickSort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCheckQuickSort))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMultiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCheckMultiplicacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPermutaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCheckPermutaciones))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCriba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCheckCriba))
                .addGap(18, 18, 18)
                .addComponent(btnReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("Benchmark");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        JDReporte reporte = new JDReporte(this, true);
        new Reporte(this, reporte);
        reporte.setLocationRelativeTo(null);
        reporte.setVisible(true);
    }//GEN-LAST:event_btnReporteActionPerformed

    private void btnQuickSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuickSortActionPerformed

        JDQuickSort jDQuickSort = new JDQuickSort(this, true);
        new QuickSort(this, jDQuickSort);
        jDQuickSort.setLocationRelativeTo(null);
        jDQuickSort.setVisible(true);

    }//GEN-LAST:event_btnQuickSortActionPerformed

    private void btnCribaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCribaActionPerformed
        JDCribaEratostenes criba = new JDCribaEratostenes(this, true);
        new CribaEratostenes(this, criba);
        criba.setLocationRelativeTo(null);
        criba.setVisible(true);
    }//GEN-LAST:event_btnCribaActionPerformed

    private void btnMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicacionActionPerformed
        JDProductoMatrices jDProductoMatrices = new JDProductoMatrices(this, true);
        new ProductoMatrices(this, jDProductoMatrices);
        jDProductoMatrices.setLocationRelativeTo(null);
        jDProductoMatrices.setVisible(true);
    }//GEN-LAST:event_btnMultiplicacionActionPerformed

    private void btnPermutacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPermutacionesActionPerformed
        JDPermutaciones per = new JDPermutaciones(this, true);
        new Permutacion(this, per);
        per.setLocationRelativeTo(null);
        per.setVisible(true);
    }//GEN-LAST:event_btnPermutacionesActionPerformed

    private void lblChangeProperty(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblChangeProperty
        if (this.lblCheckQuickSort.isEnabled() == true
                & this.lblCheckMultiplicacion.isEnabled() == true
                & this.lblCheckPermutaciones.isEnabled() == true
                & this.lblCheckCriba.isEnabled() == true) {

            this.btnReporte.setEnabled(true);
        } else {
            this.btnReporte.setEnabled(false);
        }

    }//GEN-LAST:event_lblChangeProperty

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRMBenchmark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRMBenchmark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRMBenchmark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMBenchmark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRMBenchmark().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCriba;
    public javax.swing.JButton btnMultiplicacion;
    public javax.swing.JButton btnPermutaciones;
    public javax.swing.JButton btnQuickSort;
    public javax.swing.JButton btnReporte;
    private java.awt.Button button1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lblCheckCriba;
    public javax.swing.JLabel lblCheckMultiplicacion;
    public javax.swing.JLabel lblCheckPermutaciones;
    public javax.swing.JLabel lblCheckQuickSort;
    // End of variables declaration//GEN-END:variables
}
